### ISSUE TITLE
Handle ray tracing through water

### ISSUE THREAD

**Issue by Aquaz** [REGoth-project/REGoth#66]
Right now ray trace hits the surface and stops there, I will change the current behavior so we can trace down the bottom of reservoirs and determine their depth.

**Comment by degenerated1123** [comment]
What I just remembered: The function I wrote for tracing only returns the nearest result. 
You could write one which returns all results instead, sorted by distance, and then check for the material types.

I think that would be a better approach than collision-filters for the water, because you only needed to trace once then!

**Comment by Aquaz** [comment]
Sounds good, I'll look into raytrace and BP internals when I get home this evening :)

**Comment by Aquaz** [comment]
implemented in #86
